config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :customers
  resources :students 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'companies#index'

  get '/calculators/calc' => 'calculators#calc', as: 'calc'
  get '/calculators/mean' => 'calculators#mean', as: 'mean'
  get '/calculators/median' => 'calculators#median', as: 'median'
  get '/calculators/mode' => 'calculators#mode', as: 'mode'
  
  resources :calculators
  get '/files/editFile' => 'files#editFile', as: 'editFile'
  resources :files
  
  resources :authors, except: [:edit, :update] do
    resources :books, except: [:edit, :update]
  end

  resources :users, except: [:edit, :update] do
    resources :accounts, except: [:edit, :update]
  end

  resources :physicians, :appointment

  resources :companies do
    resources :notes, module: :companies
  end
  resources :employees do
    resources :notes, module: :employees
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :patient
  belongs_to :physician
  accepts_nested_attributes_for :patient, allow_destroy: true
  # accepts_nested_attributes_for :physician, allow_destroy: true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books, :dependent => :delete_all
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :notes, as: :notable
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_many :notes, as: :notable
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :notable, polymorphic: true
end

app/models/patient.rb
class Patient < ApplicationRecord
    has_many :appointments
    has_many :physicians, through: :appointments
end

app/models/physician.rb
class Physician < ApplicationRecord
    has_many :appointments
    has_many :patients, through: :appointments   
end

app/models/player.rb
class Player < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_one :account, dependent: :destroy
    accepts_nested_attributes_for :account
end

app/controllers/appointment_controller.rb
class AppointmentController < ApplicationController
    def index
        @appointments = Appointment.all
    end

    def show
        @appointment = Appointment.find(params[:id])
    end

    def new
        @appointment = Appointment.new
    end

    def create 
        @appointment = Appointment.new(appointment_params)

            if(@appointment.save)
                redirect_to @appointment
            else
                render 'new'
            end
    end

    def destroy
        @appointment = Appointment.find(params[:id])
        @appointment.destroy
        redirect_to appointment_index_path   
    end

    private def appointment_params
        params.require(:appointment).permit(:physician_id, patient_attributes: [:name])
    end
end

app/helpers/appointment_helper.rb
module AppointmentHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/files_helper.rb
module FilesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointment/index.html.erb
<h1>Appointments</h1>
<table class='table'>
  <thead>
    <tr>
      <th>Appointment Id</th>
      <th>Doctor</th>
      <th>Patient</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.id %></td>
        <td><%= appointment.physician.name %></td>
        <td><%= appointment.patient.name %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>
<br>
<br>
<%= link_to 'Physician', physicians_path %>

app/views/appointment/new.html.erb
<h1>Add New Appointment</h1>
<%= form_for @appointment, url: appointment_index_path do |f| %> 
<%= f.fields_for :patient, Patient.new do |form| %>
<p>
    <%= form.label :patient_name%>
    <br>
    <%= form.text_field(:name, {:class => 'form-control'})%>
</p>
<%end %>
<p>
    <%= f.label :doctor%>
    <br>
    <select name="appointment[physician_id]">
    <% Physician.all.each do |physician| %>
        <option value="<%= physician.id %>"><%= physician.name %></option>
    <% end %>
</select>
</p>
<p>
    <%= f.submit({:class => 'btn btn-dark'}) %>
    
</p>

<%end%>

app/views/appointment/show.html.erb
<h1><%=@appointment.id %></h1>
<hr>
<br>
<%= link_to 'Delete', appointment_path(@appointment), method: :delete, data: {confirm: 'Are you sure?'}, :class => 'btn btn-danger' %> 
<hr>
    
        <div class="well">
        <Strong>Appointment is set!!!!</Strong> <br>
        Physician: <Strong><%= @appointment.physician.name %></Strong> <br>
        Patient: <Strong><%= @appointment.patient.name %></Strong>
        </div>
    
<hr>
    